
package transformfix;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.String;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.geom.AffineTransform;
import java.awt.geom.Area;
import java.awt.geom.Rectangle2D;
import javax.swing.JOptionPane;
import java.awt.Polygon;
import java.awt.Shape;
 
public class Transformfix extends javax.swing.JFrame {

    /**
     * Creates new form Transformfix
     */
        int x, p, y, l, s, t_1, t_2, r;
private final Color graft[][] = new Color[3000][3000];
    public Transformfix() {
        initComponents();
    }
        private void putPixel(Graphics g, int x, int y, Color color, int size) {
        try {
            Graphics g2 = (Graphics2D) g;
            g2.setColor(Color.red);
            g2.fillRect(x, y, size, size);
            int pixX = Math.abs(x);
            int pixY = Math.abs(y);
            graft[pixX][pixY] = color;
        } catch (IndexOutOfBoundsException ex) {
        } catch (Exception ex2) {
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelKontrol = new javax.swing.JPanel();
        XLabel = new javax.swing.JLabel();
        inputX = new javax.swing.JTextField();
        YLabel = new javax.swing.JLabel();
        inputY = new javax.swing.JTextField();
        btndraw = new javax.swing.JButton();
        nameTag = new javax.swing.JLabel();
        PLabel = new javax.swing.JLabel();
        inputX1 = new javax.swing.JTextField();
        LLabel = new javax.swing.JLabel();
        inputY1 = new javax.swing.JTextField();
        radius = new javax.swing.JTextField();
        YLabel1 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        tombolTranslasi = new javax.swing.JButton();
        tombolSkala = new javax.swing.JButton();
        tombolPutar = new javax.swing.JButton();
        btnShearing = new javax.swing.JButton();
        btnClipping = new javax.swing.JButton();
        btnReflectio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tempatGambar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelKontrol.setBackground(new java.awt.Color(255, 102, 102));
        panelKontrol.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        XLabel.setText("X0 ");

        inputX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputXActionPerformed(evt);
            }
        });

        YLabel.setText("Y0");

        btndraw.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btndraw.setText("Draw");
        btndraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndrawActionPerformed(evt);
            }
        });

        PLabel.setText("X1");

        inputX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputX1ActionPerformed(evt);
            }
        });

        LLabel.setText("Y1");

        radius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiusActionPerformed(evt);
            }
        });

        YLabel1.setText("Radius");

        btnclear.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKontrolLayout = new javax.swing.GroupLayout(panelKontrol);
        panelKontrol.setLayout(panelKontrolLayout);
        panelKontrolLayout.setHorizontalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelKontrolLayout.createSequentialGroup()
                                .addComponent(YLabel1)
                                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKontrolLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameTag, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(radius, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelKontrolLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(inputY1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(panelKontrolLayout.createSequentialGroup()
                                .addComponent(LLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKontrolLayout.createSequentialGroup()
                                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(XLabel)
                                        .addComponent(YLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(PLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputX1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputX, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputY, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btndraw, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        panelKontrolLayout.setVerticalGroup(
            panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKontrolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addComponent(nameTag)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelKontrolLayout.createSequentialGroup()
                        .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(XLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputY, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputX1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputY1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YLabel1)
                            .addComponent(radius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelKontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnclear)
                            .addComponent(btndraw))
                        .addGap(3, 3, 3))))
        );

        tombolTranslasi.setBackground(new java.awt.Color(0, 204, 204));
        tombolTranslasi.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        tombolTranslasi.setText("Translation");
        tombolTranslasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTranslasiActionPerformed(evt);
            }
        });

        tombolSkala.setBackground(new java.awt.Color(0, 204, 204));
        tombolSkala.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        tombolSkala.setText("Scaling");
        tombolSkala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSkalaActionPerformed(evt);
            }
        });

        tombolPutar.setBackground(new java.awt.Color(0, 204, 204));
        tombolPutar.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        tombolPutar.setText("Rotation");
        tombolPutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolPutarActionPerformed(evt);
            }
        });

        btnShearing.setBackground(new java.awt.Color(0, 204, 204));
        btnShearing.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        btnShearing.setText("Shearing");
        btnShearing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShearingActionPerformed(evt);
            }
        });

        btnClipping.setBackground(new java.awt.Color(0, 204, 204));
        btnClipping.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        btnClipping.setText("Clipping");
        btnClipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClippingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tombolTranslasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tombolPutar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnShearing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClipping, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tombolSkala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelKontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolTranslasi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tombolSkala, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolPutar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShearing, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClipping, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        btnReflectio.setBackground(new java.awt.Color(0, 204, 204));
        btnReflectio.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        btnReflectio.setText("Reflection");
        btnReflectio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReflectioActionPerformed(evt);
            }
        });

        tempatGambar.setBackground(new java.awt.Color(255, 255, 255));
        tempatGambar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout tempatGambarLayout = new javax.swing.GroupLayout(tempatGambar);
        tempatGambar.setLayout(tempatGambarLayout);
        tempatGambarLayout.setHorizontalGroup(
            tempatGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        tempatGambarLayout.setVerticalGroup(
            tempatGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tempatGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tempatGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnReflectio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReflectio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndrawActionPerformed
        // TODO add your handling code here:
        Graphics grafis = tempatGambar.getGraphics();

        if(inputX.getText().equals("") || inputY.getText().equals("") || inputX1.getText().equals("") || inputY1.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "Mohon isi semua kolom yang di sediakan");

            inputX.setText("");
            inputY.setText("");
            inputX1.setText("");
            inputY1.setText("");

        } else {

            grafis.setColor(Color.black);

            x = Integer.parseInt((String) inputX.getText());
            y = Integer.parseInt((String) inputY.getText());
            p = Integer.parseInt((String) inputX1.getText());
            l = Integer.parseInt((String) inputY1.getText());

            grafis.drawRect(x, y, p, l);
//            grafis.drawString("A", x, x);       //
//            grafis.drawString("B", x, x+p);     // persegi
//            grafis.drawString("C", x+l, x);     //
//            grafis.drawString("D", l+y,l+y);    //

            grafis.drawString("A", x, x);       //
            grafis.drawString("B", x, p);       // persegi panjang
            grafis.drawString("C", x+p, x);     //
            grafis.drawString("D", l+p,l+y);    //

            inputX.setText("");
            inputY.setText("");
            inputX1.setText("");
            inputY1.setText("");
        }

    }//GEN-LAST:event_btndrawActionPerformed

    private void inputX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputX1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_inputX1ActionPerformed

    private void radiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiusActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:

        tempatGambar.repaint();

        x = y = p = l = 0;

        inputX.setText("");
        inputY.setText("");
        inputX1.setText("");
        inputY1.setText("");
        radius.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void tombolTranslasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTranslasiActionPerformed
        // TODO add your handling code here:

        Graphics grafis = tempatGambar.getGraphics();

        if(x == 0 || y == 0 || p == 0 || l == 0 ) {
            javax.swing.JOptionPane.showMessageDialog(null, "gambar tidak ditemukan");
        } else {

            t_1 = Integer.parseInt((String) javax.swing.JOptionPane.showInputDialog("Masukkan posisi X"));
            t_2 = Integer.parseInt((String) javax.swing.JOptionPane.showInputDialog("Masukkan posisi Y"));

            grafis.setColor(Color.red);
            grafis.drawRect(x+t_1, y+t_2, p, l);

            inputX.setText("");
            inputY.setText("");
            inputX1.setText("");
            inputY1.setText("");
            t_1 = t_2 = 0;
        }
    }//GEN-LAST:event_tombolTranslasiActionPerformed
    
    private void tombolSkalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSkalaActionPerformed
        // TODO add your handling code here:
        Graphics grafis = tempatGambar.getGraphics();

        if(x == 0 || y == 0 || p == 0 || l == 0 ) {
            javax.swing.JOptionPane.showMessageDialog(null, "gambar tidak ditemukan");
        } else {

            s = (int) Double.parseDouble((String) javax.swing.JOptionPane.showInputDialog("Masukkan skala baru"));
            int high = Integer.parseInt((String) javax.swing.JOptionPane.showInputDialog("Untuk Perbesar(1), Perkecil(0)"));
            if (high == 1){
                grafis.setColor(Color.blue);
                grafis.drawRect(x, y, p*s, l*s);
            }
            else if(high == 0)
            {
                grafis.setColor(Color.green);
                grafis.drawRect(x, y, p/s, l/s);
            }
            inputX.setText("");
            inputY.setText("");
            inputX1.setText("");
            inputY1.setText("");

            s = 0;
        }

    }//GEN-LAST:event_tombolSkalaActionPerformed

    private void tombolPutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolPutarActionPerformed
        // TODO add your handling code here:
        Graphics2D grafis = (Graphics2D) tempatGambar.getGraphics();
        Rectangle rect = new Rectangle(x, y, p, l);
        int radius1 = Integer.parseInt (radius.getText());
        grafis.rotate(Math.toRadians(radius1),x,y);
        grafis.draw(rect);
    }//GEN-LAST:event_tombolPutarActionPerformed

    private void inputXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputXActionPerformed

    private void btnShearingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShearingActionPerformed
        // TODO add your handling code here:
        String s0s = JOptionPane.showInputDialog(null, "masukkan ukuran skala x  : ");
        String s0y = JOptionPane.showInputDialog(null, "masukkan ukuran skala y  : ");
        double x0 = Double.parseDouble(s0s);
        double y0 = Double.parseDouble(s0y);
                Graphics2D grafis = (Graphics2D) tempatGambar.getGraphics();
//                Rectangle rect = new Rectangle(x, y, p, l);
//                int radius1 = Integer.parseInt (radius.getText());
//                grafis.rotate(Math.toRadians(radius1),x,y);
//                grafis.draw(rect);
                AffineTransform tx2 = new AffineTransform();
                grafis.draw(new Rectangle(x, y, p, l));
                tx2.shear(x0,y0);
                grafis.setTransform(tx2);
                grafis.setPaint(Color.blue);
                grafis.draw(new Rectangle(x, y, p, l));
    }//GEN-LAST:event_btnShearingActionPerformed

    private void btnClippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClippingActionPerformed
        // TODO add your handling code here:
              Graphics grafis = tempatGambar.getGraphics();
            grafis.drawRect(50, 50, 200, 200);
            Shape shape = new java.awt.geom.Rectangle2D.Float(50, 50, 200, 200);
            grafis.setColor(Color.red);
            grafis.setClip(shape);
            x = Integer.parseInt((String) inputX.getText());
            y = Integer.parseInt((String) inputY.getText());
            p = Integer.parseInt((String) inputX1.getText());
            l = Integer.parseInt((String) inputY1.getText());
            grafis.drawRect(x, y, p, l);
//            grafis.drawString("A", x, x);       //
//            grafis.drawString("B", x, x+p);     // persegi
//            grafis.drawString("C", x+l, x);     //
//            grafis.drawString("D", l+y,l+y);    //

            grafis.drawString("A", x, x);       //
            grafis.drawString("B", x, p);       // persegi panjang
            grafis.drawString("C", x+p, x);     //
            grafis.drawString("D", l+p,l+y);    //
            inputX.setText("");
            inputY.setText("");
            inputX1.setText("");
            inputY1.setText("");
       // }
        
    }//GEN-LAST:event_btnClippingActionPerformed

    private void btnReflectioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReflectioActionPerformed
        // TODO add your handling code here:
         //  t_1 = Integer.parseInt((String) javax.swing.JOptionPane.showInputDialog("Masukkan posisi X"));
        Graphics2D g2d = (Graphics2D) tempatGambar.getGraphics();
        AffineTransform rf = new AffineTransform();
            rf.translate(x-10,0);
            rf.scale(-1,1);
            rf.translate(-x,0);
            g2d.setTransform(rf);
            g2d.setPaint(Color.green);
            g2d.draw(new Rectangle(x,y,p,l));
//            g2d.drawString("A", x, x);      //
//            g2d.drawString("B", x, x+p);    // Persegi
//            g2d.drawString("C", x+l, x);    //
//            g2d.drawString("D", l+y,l+y);   //
            g2d.drawString("A", x, x);       //
            g2d.drawString("B", x, p);       // persegi panjang
            g2d.drawString("C", x+p, x);     //
            g2d.drawString("D", l+p,l+y);    //
//        if (t_1==1){
//            rf.translate(x-10,0);
//            rf.scale(-1,1);
//            rf.translate(-x,0);
//            g2d.setTransform(rf);
//            g2d.setPaint(Color.green);
//            g2d.draw(new Rectangle(x,y,p,l));
//            g2d.drawString("A", x, x);      //
//            g2d.drawString("B", x, x+p);    // Persegi
//            g2d.drawString("C", x+l, x);    //
//            g2d.drawString("D", l+y,l+y);   //
//        }  else if (t_1==2){
//            rf.translate(x,0);
//            rf.scale(2,-1);
//            rf.translate(-x,0);
//            g2d.setTransform(rf);
//            g2d.setPaint(Color.black);
//            g2d.draw(new Rectangle(x,y,p,l));
//        }
    }//GEN-LAST:event_btnReflectioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transformfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transformfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transformfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transformfix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transformfix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LLabel;
    private javax.swing.JLabel PLabel;
    private javax.swing.JLabel XLabel;
    private javax.swing.JLabel YLabel;
    private javax.swing.JLabel YLabel1;
    private javax.swing.JButton btnClipping;
    private javax.swing.JButton btnReflectio;
    private javax.swing.JButton btnShearing;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndraw;
    private javax.swing.JTextField inputX;
    private javax.swing.JTextField inputX1;
    private javax.swing.JTextField inputY;
    private javax.swing.JTextField inputY1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameTag;
    private javax.swing.JPanel panelKontrol;
    private javax.swing.JTextField radius;
    private javax.swing.JPanel tempatGambar;
    private javax.swing.JButton tombolPutar;
    private javax.swing.JButton tombolSkala;
    private javax.swing.JButton tombolTranslasi;
    // End of variables declaration//GEN-END:variables
}
